### ISSUE TITLE
ansi color suport

### ISSUE THREAD

**Issue by igotcha** [peterh/liner#34] opened 2015-02-02 08:39 UTC
hi,  I try add some color to prompt, but it seems not working properly.
would you please support this?

**Comment by peterh** [comment] 2015-02-02 14:28
Sorry, no. Cross-platform colour support is a huge amount of work (or a large amount of work plus an external dependency).

This is a duplicate of #29. Perhaps you and @gabriel-comeau could work together on a fork.

**Closed by peterh** 2015-02-02 14:28 UTC
