### ISSUE TITLE
default text after prompt?

### ISSUE THREAD

**Issue by danke-click** [peterh/liner#44] opened 2015-04-22 09:22 UTC
**Thank you** for this amazing pice a code!
I'd like to offer a default text after the prompt that can be corrected/edited by the user. Is that possible? Or is there a workaround? **thx**

**myPrompt>** default text for correction

**Comment by peterh** [comment] 2015-04-22 15:05
This is a duplicate of #38. I'm still willing to review a pull request for this feature.

**Closed by peterh** 2015-04-22 15:05 UTC
